---
databaseUrl: jdbc:mysql://localhost:3306/barcodeproject
databaseUser: picrin
databasePassword: password
allowedOrigin: http://.*:8100,http://.*:8080
ldapUrl: ad2.ad.dcs.gla.ac.uk
ldapPort: 389
adminPswdHash: ZGNzLmdsYS5hYy51aw==OyqIIctsp4T/EVstja0Qcw==
